{appl_spec,"db_etcd",
 [
     {appl_name,"db_etcd"},
     {vsn,"0.1.0"},
     {app,db_etcd},
     {gitpath,"https://github.com/joq62/db_etcd.git"},
     {local_resource_type,[db_etcd]},
     {target_resource_type,[nodelog]},
     {num_instances,},
     {affinity,any_host}
 ]}.
