{appl_spec,"hw_conbee",
 [
     {appl_name,"hw_conbee"},
     {vsn,"0.1.0"},
     {app,hw_conbee_app},
     {gitpath,"https://github.com/joq62/hw_conbee_app.git"},
     {local_resource_type,[hw_conbee]},
     {target_resource_type,[nodelog]}
 ]}.
