{appl_spec,"nodelog",
 [
     {appl_name,"nodelog"},
     {vsn,"0.1.0"},
     {app,nodelog},
     {gitpath,"https://github.com/joq62/nodelog.git"},
     {local_resource_type,[nodelog]},
     {target_resource_type,[]}
 ]}.
